/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// GroupListerExpansion allows custom methods to be added to
// GroupLister.
type GroupListerExpansion interface{}

// GroupNamespaceListerExpansion allows custom methods to be added to
// GroupNamespaceLister.
type GroupNamespaceListerExpansion interface{}

// GroupMemberListerExpansion allows custom methods to be added to
// GroupMemberLister.
type GroupMemberListerExpansion interface{}

// GroupMemberNamespaceListerExpansion allows custom methods to be added to
// GroupMemberNamespaceLister.
type GroupMemberNamespaceListerExpansion interface{}

// InfrastructureListerExpansion allows custom methods to be added to
// InfrastructureLister.
type InfrastructureListerExpansion interface{}

// InfrastructureNamespaceListerExpansion allows custom methods to be added to
// InfrastructureNamespaceLister.
type InfrastructureNamespaceListerExpansion interface{}

// LocalConfigListerExpansion allows custom methods to be added to
// LocalConfigLister.
type LocalConfigListerExpansion interface{}

// LocalConfigNamespaceListerExpansion allows custom methods to be added to
// LocalConfigNamespaceLister.
type LocalConfigNamespaceListerExpansion interface{}

// PrincipalListerExpansion allows custom methods to be added to
// PrincipalLister.
type PrincipalListerExpansion interface{}

// PrincipalNamespaceListerExpansion allows custom methods to be added to
// PrincipalNamespaceLister.
type PrincipalNamespaceListerExpansion interface{}

// TokenListerExpansion allows custom methods to be added to
// TokenLister.
type TokenListerExpansion interface{}

// TokenNamespaceListerExpansion allows custom methods to be added to
// TokenNamespaceLister.
type TokenNamespaceListerExpansion interface{}

// UserListerExpansion allows custom methods to be added to
// UserLister.
type UserListerExpansion interface{}

// UserNamespaceListerExpansion allows custom methods to be added to
// UserNamespaceLister.
type UserNamespaceListerExpansion interface{}
