/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cnrancher/cube-apiserver/k8s/pkg/apis/cube/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocalConfigs implements LocalConfigInterface
type FakeLocalConfigs struct {
	Fake *FakeCubeV1alpha1
	ns   string
}

var localconfigsResource = schema.GroupVersionResource{Group: "cube.rancher.io", Version: "v1alpha1", Resource: "localconfigs"}

var localconfigsKind = schema.GroupVersionKind{Group: "cube.rancher.io", Version: "v1alpha1", Kind: "LocalConfig"}

// Get takes name of the localConfig, and returns the corresponding localConfig object, and an error if there is any.
func (c *FakeLocalConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.LocalConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(localconfigsResource, c.ns, name), &v1alpha1.LocalConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalConfig), err
}

// List takes label and field selectors, and returns the list of LocalConfigs that match those selectors.
func (c *FakeLocalConfigs) List(opts v1.ListOptions) (result *v1alpha1.LocalConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(localconfigsResource, localconfigsKind, c.ns, opts), &v1alpha1.LocalConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LocalConfigList{ListMeta: obj.(*v1alpha1.LocalConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.LocalConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localConfigs.
func (c *FakeLocalConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(localconfigsResource, c.ns, opts))

}

// Create takes the representation of a localConfig and creates it.  Returns the server's representation of the localConfig, and an error, if there is any.
func (c *FakeLocalConfigs) Create(localConfig *v1alpha1.LocalConfig) (result *v1alpha1.LocalConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(localconfigsResource, c.ns, localConfig), &v1alpha1.LocalConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalConfig), err
}

// Update takes the representation of a localConfig and updates it. Returns the server's representation of the localConfig, and an error, if there is any.
func (c *FakeLocalConfigs) Update(localConfig *v1alpha1.LocalConfig) (result *v1alpha1.LocalConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(localconfigsResource, c.ns, localConfig), &v1alpha1.LocalConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalConfig), err
}

// Delete takes name of the localConfig and deletes it. Returns an error if one occurs.
func (c *FakeLocalConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(localconfigsResource, c.ns, name), &v1alpha1.LocalConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocalConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(localconfigsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.LocalConfigList{})
	return err
}

// Patch applies the patch and returns the patched localConfig.
func (c *FakeLocalConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.LocalConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(localconfigsResource, c.ns, name, data, subresources...), &v1alpha1.LocalConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalConfig), err
}
