/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cnrancher/cube-apiserver/k8s/pkg/apis/cube/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePrincipals implements PrincipalInterface
type FakePrincipals struct {
	Fake *FakeCubeV1alpha1
	ns   string
}

var principalsResource = schema.GroupVersionResource{Group: "cube.rancher.io", Version: "v1alpha1", Resource: "principals"}

var principalsKind = schema.GroupVersionKind{Group: "cube.rancher.io", Version: "v1alpha1", Kind: "Principal"}

// Get takes name of the principal, and returns the corresponding principal object, and an error if there is any.
func (c *FakePrincipals) Get(name string, options v1.GetOptions) (result *v1alpha1.Principal, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(principalsResource, c.ns, name), &v1alpha1.Principal{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Principal), err
}

// List takes label and field selectors, and returns the list of Principals that match those selectors.
func (c *FakePrincipals) List(opts v1.ListOptions) (result *v1alpha1.PrincipalList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(principalsResource, principalsKind, c.ns, opts), &v1alpha1.PrincipalList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PrincipalList{ListMeta: obj.(*v1alpha1.PrincipalList).ListMeta}
	for _, item := range obj.(*v1alpha1.PrincipalList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested principals.
func (c *FakePrincipals) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(principalsResource, c.ns, opts))

}

// Create takes the representation of a principal and creates it.  Returns the server's representation of the principal, and an error, if there is any.
func (c *FakePrincipals) Create(principal *v1alpha1.Principal) (result *v1alpha1.Principal, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(principalsResource, c.ns, principal), &v1alpha1.Principal{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Principal), err
}

// Update takes the representation of a principal and updates it. Returns the server's representation of the principal, and an error, if there is any.
func (c *FakePrincipals) Update(principal *v1alpha1.Principal) (result *v1alpha1.Principal, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(principalsResource, c.ns, principal), &v1alpha1.Principal{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Principal), err
}

// Delete takes name of the principal and deletes it. Returns an error if one occurs.
func (c *FakePrincipals) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(principalsResource, c.ns, name), &v1alpha1.Principal{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePrincipals) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(principalsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PrincipalList{})
	return err
}

// Patch applies the patch and returns the patched principal.
func (c *FakePrincipals) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Principal, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(principalsResource, c.ns, name, data, subresources...), &v1alpha1.Principal{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Principal), err
}
