/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cnrancher/cube-apiserver/k8s/pkg/apis/cube/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGroupMembers implements GroupMemberInterface
type FakeGroupMembers struct {
	Fake *FakeCubeV1alpha1
	ns   string
}

var groupmembersResource = schema.GroupVersionResource{Group: "cube.rancher.io", Version: "v1alpha1", Resource: "groupmembers"}

var groupmembersKind = schema.GroupVersionKind{Group: "cube.rancher.io", Version: "v1alpha1", Kind: "GroupMember"}

// Get takes name of the groupMember, and returns the corresponding groupMember object, and an error if there is any.
func (c *FakeGroupMembers) Get(name string, options v1.GetOptions) (result *v1alpha1.GroupMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(groupmembersResource, c.ns, name), &v1alpha1.GroupMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GroupMember), err
}

// List takes label and field selectors, and returns the list of GroupMembers that match those selectors.
func (c *FakeGroupMembers) List(opts v1.ListOptions) (result *v1alpha1.GroupMemberList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(groupmembersResource, groupmembersKind, c.ns, opts), &v1alpha1.GroupMemberList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GroupMemberList{ListMeta: obj.(*v1alpha1.GroupMemberList).ListMeta}
	for _, item := range obj.(*v1alpha1.GroupMemberList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested groupMembers.
func (c *FakeGroupMembers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(groupmembersResource, c.ns, opts))

}

// Create takes the representation of a groupMember and creates it.  Returns the server's representation of the groupMember, and an error, if there is any.
func (c *FakeGroupMembers) Create(groupMember *v1alpha1.GroupMember) (result *v1alpha1.GroupMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(groupmembersResource, c.ns, groupMember), &v1alpha1.GroupMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GroupMember), err
}

// Update takes the representation of a groupMember and updates it. Returns the server's representation of the groupMember, and an error, if there is any.
func (c *FakeGroupMembers) Update(groupMember *v1alpha1.GroupMember) (result *v1alpha1.GroupMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(groupmembersResource, c.ns, groupMember), &v1alpha1.GroupMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GroupMember), err
}

// Delete takes name of the groupMember and deletes it. Returns an error if one occurs.
func (c *FakeGroupMembers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(groupmembersResource, c.ns, name), &v1alpha1.GroupMember{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGroupMembers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(groupmembersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.GroupMemberList{})
	return err
}

// Patch applies the patch and returns the patched groupMember.
func (c *FakeGroupMembers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GroupMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(groupmembersResource, c.ns, name, data, subresources...), &v1alpha1.GroupMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GroupMember), err
}
