/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cnrancher/cube-apiserver/k8s/pkg/apis/cube/v1alpha1"
	scheme "github.com/cnrancher/cube-apiserver/k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GroupMembersGetter has a method to return a GroupMemberInterface.
// A group's client should implement this interface.
type GroupMembersGetter interface {
	GroupMembers(namespace string) GroupMemberInterface
}

// GroupMemberInterface has methods to work with GroupMember resources.
type GroupMemberInterface interface {
	Create(*v1alpha1.GroupMember) (*v1alpha1.GroupMember, error)
	Update(*v1alpha1.GroupMember) (*v1alpha1.GroupMember, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.GroupMember, error)
	List(opts v1.ListOptions) (*v1alpha1.GroupMemberList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GroupMember, err error)
	GroupMemberExpansion
}

// groupMembers implements GroupMemberInterface
type groupMembers struct {
	client rest.Interface
	ns     string
}

// newGroupMembers returns a GroupMembers
func newGroupMembers(c *CubeV1alpha1Client, namespace string) *groupMembers {
	return &groupMembers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the groupMember, and returns the corresponding groupMember object, and an error if there is any.
func (c *groupMembers) Get(name string, options v1.GetOptions) (result *v1alpha1.GroupMember, err error) {
	result = &v1alpha1.GroupMember{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("groupmembers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GroupMembers that match those selectors.
func (c *groupMembers) List(opts v1.ListOptions) (result *v1alpha1.GroupMemberList, err error) {
	result = &v1alpha1.GroupMemberList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("groupmembers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested groupMembers.
func (c *groupMembers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("groupmembers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a groupMember and creates it.  Returns the server's representation of the groupMember, and an error, if there is any.
func (c *groupMembers) Create(groupMember *v1alpha1.GroupMember) (result *v1alpha1.GroupMember, err error) {
	result = &v1alpha1.GroupMember{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("groupmembers").
		Body(groupMember).
		Do().
		Into(result)
	return
}

// Update takes the representation of a groupMember and updates it. Returns the server's representation of the groupMember, and an error, if there is any.
func (c *groupMembers) Update(groupMember *v1alpha1.GroupMember) (result *v1alpha1.GroupMember, err error) {
	result = &v1alpha1.GroupMember{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("groupmembers").
		Name(groupMember.Name).
		Body(groupMember).
		Do().
		Into(result)
	return
}

// Delete takes name of the groupMember and deletes it. Returns an error if one occurs.
func (c *groupMembers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("groupmembers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *groupMembers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("groupmembers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched groupMember.
func (c *groupMembers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GroupMember, err error) {
	result = &v1alpha1.GroupMember{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("groupmembers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
