/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cnrancher/cube-apiserver/k8s/pkg/apis/cube/v1alpha1"
	scheme "github.com/cnrancher/cube-apiserver/k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LocalConfigsGetter has a method to return a LocalConfigInterface.
// A group's client should implement this interface.
type LocalConfigsGetter interface {
	LocalConfigs(namespace string) LocalConfigInterface
}

// LocalConfigInterface has methods to work with LocalConfig resources.
type LocalConfigInterface interface {
	Create(*v1alpha1.LocalConfig) (*v1alpha1.LocalConfig, error)
	Update(*v1alpha1.LocalConfig) (*v1alpha1.LocalConfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.LocalConfig, error)
	List(opts v1.ListOptions) (*v1alpha1.LocalConfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.LocalConfig, err error)
	LocalConfigExpansion
}

// localConfigs implements LocalConfigInterface
type localConfigs struct {
	client rest.Interface
	ns     string
}

// newLocalConfigs returns a LocalConfigs
func newLocalConfigs(c *CubeV1alpha1Client, namespace string) *localConfigs {
	return &localConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the localConfig, and returns the corresponding localConfig object, and an error if there is any.
func (c *localConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.LocalConfig, err error) {
	result = &v1alpha1.LocalConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("localconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LocalConfigs that match those selectors.
func (c *localConfigs) List(opts v1.ListOptions) (result *v1alpha1.LocalConfigList, err error) {
	result = &v1alpha1.LocalConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("localconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested localConfigs.
func (c *localConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("localconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a localConfig and creates it.  Returns the server's representation of the localConfig, and an error, if there is any.
func (c *localConfigs) Create(localConfig *v1alpha1.LocalConfig) (result *v1alpha1.LocalConfig, err error) {
	result = &v1alpha1.LocalConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("localconfigs").
		Body(localConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a localConfig and updates it. Returns the server's representation of the localConfig, and an error, if there is any.
func (c *localConfigs) Update(localConfig *v1alpha1.LocalConfig) (result *v1alpha1.LocalConfig, err error) {
	result = &v1alpha1.LocalConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("localconfigs").
		Name(localConfig.Name).
		Body(localConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the localConfig and deletes it. Returns an error if one occurs.
func (c *localConfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("localconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *localConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("localconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched localConfig.
func (c *localConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.LocalConfig, err error) {
	result = &v1alpha1.LocalConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("localconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
