/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cnrancher/cube-apiserver/k8s/pkg/apis/cube/v1alpha1"
	scheme "github.com/cnrancher/cube-apiserver/k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PrincipalsGetter has a method to return a PrincipalInterface.
// A group's client should implement this interface.
type PrincipalsGetter interface {
	Principals(namespace string) PrincipalInterface
}

// PrincipalInterface has methods to work with Principal resources.
type PrincipalInterface interface {
	Create(*v1alpha1.Principal) (*v1alpha1.Principal, error)
	Update(*v1alpha1.Principal) (*v1alpha1.Principal, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Principal, error)
	List(opts v1.ListOptions) (*v1alpha1.PrincipalList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Principal, err error)
	PrincipalExpansion
}

// principals implements PrincipalInterface
type principals struct {
	client rest.Interface
	ns     string
}

// newPrincipals returns a Principals
func newPrincipals(c *CubeV1alpha1Client, namespace string) *principals {
	return &principals{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the principal, and returns the corresponding principal object, and an error if there is any.
func (c *principals) Get(name string, options v1.GetOptions) (result *v1alpha1.Principal, err error) {
	result = &v1alpha1.Principal{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("principals").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Principals that match those selectors.
func (c *principals) List(opts v1.ListOptions) (result *v1alpha1.PrincipalList, err error) {
	result = &v1alpha1.PrincipalList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("principals").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested principals.
func (c *principals) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("principals").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a principal and creates it.  Returns the server's representation of the principal, and an error, if there is any.
func (c *principals) Create(principal *v1alpha1.Principal) (result *v1alpha1.Principal, err error) {
	result = &v1alpha1.Principal{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("principals").
		Body(principal).
		Do().
		Into(result)
	return
}

// Update takes the representation of a principal and updates it. Returns the server's representation of the principal, and an error, if there is any.
func (c *principals) Update(principal *v1alpha1.Principal) (result *v1alpha1.Principal, err error) {
	result = &v1alpha1.Principal{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("principals").
		Name(principal.Name).
		Body(principal).
		Do().
		Into(result)
	return
}

// Delete takes name of the principal and deletes it. Returns an error if one occurs.
func (c *principals) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("principals").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *principals) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("principals").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched principal.
func (c *principals) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Principal, err error) {
	result = &v1alpha1.Principal{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("principals").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
